Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
model_after = run_training(model, optimizer, epochs=10)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[17], line 1[0m
[0;32m----> 1[0m model_after [38;5;241m=[39m [43mrun_training[49m[43m([49m[43mmodel[49m[43m,[49m[43m [49m[43moptimizer[49m[43m,[49m[43m [49m[43mepochs[49m[38;5;241;43m=[39;49m[38;5;241;43m10[39;49m[43m)[49m

Cell [0;32mIn[14], line 9[0m, in [0;36mrun_training[0;34m(model, optimizer, epochs)[0m
[1;32m      5[0m accuracies [38;5;241m=[39m []
[1;32m      7[0m torch[38;5;241m.[39mautograd[38;5;241m.[39mset_detect_anomaly([38;5;28;01mTrue[39;00m)
[0;32m----> 9[0m [38;5;28;01mfor[39;00m epoch [38;5;129;01min[39;00m [43mtrange[49m[43m([49m[43mepochs[49m[43m)[49m:
[1;32m     10[0m     training_loss, mean_loss [38;5;241m=[39m train(model, DEVICE, train_loader, optimizer, epoch, max_epochs[38;5;241m=[39mEPOCHS)
[1;32m     11[0m     test_loss, accuracy [38;5;241m=[39m test(model, DEVICE, test_loader, epoch)

File [0;32m/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/tqdm/notebook.py:311[0m, in [0;36mtnrange[0;34m(*args, **kwargs)[0m
[1;32m    309[0m [38;5;28;01mdef[39;00m [38;5;21mtnrange[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    310[0m [38;5;250m    [39m[38;5;124;03m"""Shortcut for `tqdm.notebook.tqdm(range(*args), **kwargs)`."""[39;00m
[0;32m--> 311[0m     [38;5;28;01mreturn[39;00m [43mtqdm_notebook[49m[43m([49m[38;5;28;43mrange[39;49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/tqdm/notebook.py:233[0m, in [0;36mtqdm_notebook.__init__[0;34m(self, *args, **kwargs)[0m
[1;32m    231[0m unit_scale [38;5;241m=[39m [38;5;241m1[39m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39munit_scale [38;5;129;01mis[39;00m [38;5;28;01mTrue[39;00m [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39munit_scale [38;5;129;01mor[39;00m [38;5;241m1[39m
[1;32m    232[0m total [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtotal [38;5;241m*[39m unit_scale [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mtotal [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39mtotal
[0;32m--> 233[0m [38;5;28mself[39m[38;5;241m.[39mcontainer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mstatus_printer[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfp[49m[43m,[49m[43m [49m[43mtotal[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdesc[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mncols[49m[43m)[49m
[1;32m    234[0m [38;5;28mself[39m[38;5;241m.[39mcontainer[38;5;241m.[39mpbar [38;5;241m=[39m proxy([38;5;28mself[39m)
[1;32m    235[0m [38;5;28mself[39m[38;5;241m.[39mdisplayed [38;5;241m=[39m [38;5;28;01mFalse[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/tqdm/notebook.py:108[0m, in [0;36mtqdm_notebook.status_printer[0;34m(_, total, desc, ncols)[0m
[1;32m     99[0m [38;5;66;03m# Fallback to text bar if there's no total[39;00m
[1;32m    100[0m [38;5;66;03m# DEPRECATED: replaced with an 'info' style bar[39;00m
[1;32m    101[0m [38;5;66;03m# if not total:[39;00m
[0;32m   (...)[0m
[1;32m    105[0m 
[1;32m    106[0m [38;5;66;03m# Prepare IPython progress bar[39;00m
[1;32m    107[0m [38;5;28;01mif[39;00m IProgress [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:  [38;5;66;03m# #187 #451 #558 #872[39;00m
[0;32m--> 108[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(WARN_NOIPYW)
[1;32m    109[0m [38;5;28;01mif[39;00m total:
[1;32m    110[0m     pbar [38;5;241m=[39m IProgress([38;5;28mmin[39m[38;5;241m=[39m[38;5;241m0[39m, [38;5;28mmax[39m[38;5;241m=[39mtotal)

[0;31mImportError[0m: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

